### ISSUE TITLE
Logo and search bar in header

### ISSUE THREAD

**Issue by stevebrownlee** [nss-day-cohort-20/group-project-theme-park-2-funnelcake#1]
# Story

As a user, in order to find attractions I'm interested in, I need to type some value in a text box in the navigation bar at the top of the page, press enter, and see results

# Acceptance Criteria

**Given** a user visits the application
**When** the application renders
**Then** the application logo should appear on the left in a navigation bar

**Given** a user visits the application
**When** the application renders
**Then** a text field should appear in the middle of the navigation bar

**Given** the user types some characters into the search field
**When** user user presses enter
**Then** the areas that contain an attraction, whose name contains the search string, should be outlined with a border

# Technical Information

1. Use regular expressions to match the user's search string with the name of each attraction to find a match. The search string simply must be contained in the attraction name, not just start with.

**Comment by cait-rocco** [comment]
- [x] search bar in nav
- [x] event listener on enter
- [x]  Use regular expressions to match the user's search string with the name of each attraction to find a match 
- [x] match attraction with areas that contain an attraction, whose name contains the search string (seperate function reused in area click #3?)
- [x] area should be outlined with a border
