### ISSUE TITLE
User click on area shows attractions

### ISSUE THREAD

**Issue by stevebrownlee** [nss-day-cohort-20/group-project-theme-park-2-funnelcake#3]
# Story

As a user, in order to explore attractions near me, I need to highlight an area of the park and see all attractions in it

# Acceptance Criteria

**Given** user wants to see the attraction list of an area
**When** the user clicks on an area
**Then** all attraction names assigned to that area should be listed in the left 30% of the screen
**And** the attraction type should be in parenthesis next to the name
**And** the name should be a hyperlink

**Comment by cait-rocco** [comment]
- [x] event listener on area click
- [x] find attractions with matching area id  (seperate function reused in area click #3?)
- [x] displays attractions in that area
- [x] display shows hyperlinked attraction with (attraction type) [similar to display for time   #6  covered in  #4 )
