### ISSUE TITLE
User should be able to see attraction details

### ISSUE THREAD

**Issue by stevebrownlee** [nss-day-cohort-20/group-project-theme-park-2-funnelcake#4]
# Story

As a user, in order to see when a ride is open, I need to be able to select a ride and see all available information about it

# Acceptance Criteria

**Given** the user has clicked on an area
**When** the user clicks on a specific attraction's hyperlink
**Then** the description of the attraction, and its hours of operation must be displayed directly beneath the hyperlink, and before the next one
**And** any previously displayed attraction details must disappear

**Comment by cait-rocco** [comment]
- [ ] event listener on hyperlink click
- [ ] display attraction type beside it (matched by id)
- [ ] attractions that appear in left list are hyperlinked. when clicked on details & hours appear below
- [ ] when clicked on, details displayed for other attractions disappear
