### ISSUE TITLE
User should be able to see rides open at a specific time

### ISSUE THREAD

**Issue by stevebrownlee** [nss-day-cohort-20/group-project-theme-park-2-funnelcake#6]
# Story

As a user, in order plan my trip through the park, I need to be able to see which rides are open at a particular hour of the day

# Acceptance Criteria

**Given** the user wants to see all attractions operating at a specific hour
**When** the user performs a gesture on a time selection element above the park grid
**Then** all attractions that operate at that hour should be listed in the left 30% of the screen
**And** the attraction type should be in parenthesis next to the name
**And** the name should be a hyperlink

# Technical Resource

1. You can use [Bootstrap Material DatePicker's Time Picker widget](http://t00rk.github.io/bootstrap-material-datetimepicker/) if you like. It 👌

**Comment by cait-rocco** [comment]
- [ ] time selection element
- [ ] event listener on time element
- [ ] user entered time searches attractions matching the selected time
- [ ] attractions display in left side with hyperlinks and (attraction type)
- [ ] also displays attractions with no times
